### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by pofulu** [andrew-raphael-lukasik/pngcs#5]
I tried the following code and got this error.

> IndexOutOfRangeException: Index was outside the bounds of the array.
> Pngcs.PngWriter.EncodeRowFromInt (System.Int32[] row) (at Assets/pngcs-master/Pngcs/PngWriter.cs:270)
> Pngcs.PngWriter.WriteRowInt (System.Int32[] newrow, System.Int32 rown) (at Assets/pngcs-master/Pngcs/PngWriter.cs:549)
> Pngcs.PngWriter.WriteRow (Pngcs.ImageLine line, System.Int32 rownumber) (at Assets/pngcs-master/Pngcs/PngWriter.cs:530)
> Pngcs.Unity.PNG.Write (UnityEngine.Color[] pixels, System.Int32 width, System.Int32 height, System.Int32 bitDepth, System.Boolean alpha, System.Boolean greyscale, System.String filePath) (at Assets/pngcs-master/Pngcs/Unity/Unity.cs:238)
> Pngcs.Unity.PNG.Write (UnityEngine.Texture2D texture, System.String filePath) (at Assets/pngcs-master/Pngcs/Unity/Unity.cs:152)
> PngcsTest+<Start>d__0.MoveNext () (at Assets/pngcs-master/PngcsTest.cs:15)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

```C#
IEnumerator Start()
{
    yield return new WaitForEndOfFrame();

    var texture = ScreenCapture.CaptureScreenshotAsTexture();
    var output = Path.Combine(Application.persistentDataPath, "test.png");

    PNG.Write(texture, output);
}
```

**Comment by andrew-raphael-lukasik** [comment]
6c340b6 fixed this

**Comment by andrew-raphael-lukasik** [comment]
Thanks for reporting!
